.vscode/launch.json, force-app/main/default/lwc/commonStyles/commonStyles.js-meta.xml, force-app/main/default/lwc/createAccountRecord/__tests__/createAccountRecord.test.js, force-app/main/default/lwc/createAccountRecord/createAccountRecord.html, force-app/main/default/lwc/createAccountRecord/createAccountRecord.js, force-app/main/default/lwc/createAccountRecord/createAccountRecord.js-meta.xml, force-app/main/default/lwc/createContactRecord/__tests__/createContactRecord.test.js, force-app/main/default/lwc/createContactRecord/createContactRecord.html, force-app/main/default/lwc/createContactRecord/createContactRecord.js, force-app/main/default/lwc/createContactRecord/createContactRecord.js-meta.xml, force-app/main/default/lwc/editAccountRecord/__tests__/editAccountRecord.test.js, force-app/main/default/lwc/editAccountRecord/editAccountRecord.html, force-app/main/default/lwc/editAccountRecord/editAccountRecord.js, force-app/main/default/lwc/editAccountRecord/editAccountRecord.js-meta.xml, force-app/main/default/lwc/editContactRecord/__tests__/editContactRecord.test.js, force-app/main/default/lwc/editContactRecord/editContactRecord.html, force-app/main/default/lwc/editContactRecord/editContactRecord.js, force-app/main/default/lwc/editContactRecord/editContactRecord.js-meta.xml, force-app/main/default/lwc/viewAccountRecord/viewAccountRecord.js-meta.xml, force-app/main/default/lwc/viewContactRecord/viewContactRecord.js-meta.xml, jest.config.js, package-lock.json, package.json, sfdx-project.json
Here's an initial PR for the createAccountRecord functionality. Basically, just adding back in unit tests and want to get your thoughts?
@khawkins
=> Cleaning up tests for createAccountRecord.

.github/workflows/lint.yml, .github/workflows/prettier.yml, .github/workflows/run-tests.yml, .vscode/extensions.json, .vscode/settings.json, force-app/main/default/lwc/createAccountRecord/__tests__/createAccountRecord.test.js, force-app/main/default/lwc/createAccountRecord/createAccountRecord.js, force-app/main/default/lwc/editAccountRecord/__tests__/editAccountRecord.test.js, force-app/main/default/lwc/editAccountRecord/editAccountRecord.js, force-app/main/default/lwc/errorPanel/__tests__/errorPanel.test.js, force-app/main/default/lwc/errorPanel/errorPanel.js, force-app/main/default/lwc/ldsUtils/__tests__/ldsUtils.test.js, force-app/main/default/lwc/ldsUtils/ldsUtils.js, force-app/main/default/lwc/scanBarcode/__mocks__/lightning/mobileCapabilities.js, force-app/main/default/lwc/scanBarcode/__tests__/scanBarcode.test.js, force-app/main/default/lwc/scanBarcode/scanBarcode.js, force-app/main/default/lwc/viewAccountRecord/__tests__/viewAccountRecord.test.js, force-app/main/default/lwc/viewAccountRecord/viewAccountRecord.js, force-app/main/default/lwc/viewAccountsWithApex/__tests__/viewAccountsWithApex.test.js, force-app/main/default/lwc/viewAccountsWithApex/viewAccountsWithApex.js, package-lock.json, package.json
Fear not, the terrible large changes! I broke the commits up into meaningful chunks, with the last commit being *exclusively* format changes from running `prettier` on the `force-app/**/*.js` files. I'd just ignore that commit, from a review standpoint.
I'd recommend clicking through each of the first 3 commits, one by one, which are not nearly so noisy, and represent the interesting changes to the repo, which are:
- Added Prettier and ESLint as suggested VSCode extensions.
- Updated JS editors to run Prettier on file save.
- Fixed the outstanding ESLint errors in the project.
- Added GitHub Actions CI for all of the above, to keep us honest on PRs going forward.
=> Adding CI, ESLint, Prettier checks

README.md, force-app/main/default/lwc/viewAccountRecord/viewAccountRecord.html, force-app/main/default/lwc/viewAccountRecord/viewAccountRecord.js
Instead, it is currently recommended to not use layouts and to specify field values for mobile clients due to offline edge cases.
@khawkins @AdamLiechty
=> Updating to remove unsupported getRecord with layout value.

force-app/main/default/lwc/scanBarcode/__tests__/scanBarcode.test.js, force-app/main/default/lwc/scanBarcode/scanBarcode.html, force-app/main/default/lwc/scanBarcode/scanBarcode.js, package-lock.json, package.json
Update the code for barcode scanner error handling. Below are screenshots of when an error occurs and when the user successfully scans something:
=> Update code for barcode scanner error handling

force-app/main/default/lwc/commonStyles/commonStyles.css, force-app/main/default/lwc/createAccountRecord/createAccountRecord.html, force-app/main/default/lwc/editAccountRecord/editAccountRecord.css, force-app/main/default/lwc/editAccountRecord/editAccountRecord.html, force-app/main/default/lwc/viewAccountRecord/viewAccountRecord.css, force-app/main/default/lwc/viewAccountRecord/viewAccountRecord.html
Attempting to get closer to UX suggestions. The record name/object type still looks off to me, but the icon is 32x32 and font size is 14pt.
Updated screen shots showing changes in Test Harness: 
@khawkins @AdamLiechty
=> Adding UX suggestions.

.forceignore
Fixes failure to deploy:
```sh
sfdx force:source:deploy --sourcepath=./force-app -u MY_ALIAS
Error __mocks__ Cannot find Lightning Component Bundle __mocks__.
```
=> @W-13093077 Update .forceignore for __mocks__

force-app/main/default/lwc/createContactRecord/__tests__/createContactRecord.test.js, force-app/main/default/lwc/createContactRecord/createContactRecord.css, force-app/main/default/lwc/createContactRecord/createContactRecord.html, force-app/main/default/lwc/createContactRecord/createContactRecord.js, force-app/main/default/lwc/createContactRecord/createContactRecord.js-meta.xml, force-app/main/default/lwc/createOpportunityRecord/__tests__/createOpportunityRecord.test.js, force-app/main/default/lwc/createOpportunityRecord/createOpportunityRecord.css, force-app/main/default/lwc/createOpportunityRecord/createOpportunityRecord.html, force-app/main/default/lwc/createOpportunityRecord/createOpportunityRecord.js, force-app/main/default/lwc/createOpportunityRecord/createOpportunityRecord.js-meta.xml
@AdamLiechty @khawkins @sfdctaka @maliroteh-sf 
(Not sure yet if lookup fields are supported or not -- waiting on clarification.)
=> Create contact record and Create opportunity record.

README.md
@khawkins @sfdctaka @maliroteh-sf
=> Updating steps to include checking out the appropriate tag.

force-app/main/default/staticresources/landing_page_case_management.json, force-app/main/default/staticresources/landing_page_case_management.resource-meta.xml, force-app/main/default/staticresources/landing_page_default.json, force-app/main/default/staticresources/landing_page_default.resource-meta.xml, force-app/main/default/staticresources/landing_page_healthcare.json, force-app/main/default/staticresources/landing_page_healthcare.resource-meta.xml, force-app/main/default/staticresources/landing_page_retail_execution.json, force-app/main/default/staticresources/landing_page_retail_execution.resource-meta.xml
Includes:
Landing Page Default - Shipped with the client
Case Management use case
Healthcare use case
Retail Execution use case
=> Adding Landing Page Templates for various use cases

force-app/main/default/lwc/accountRelatedContacts/accountRelatedContacts.js
Use the class property method recommended to ensure priming is successful
=> Adjust GraphQL starter kit LWC 

.vscode/extensions.json
It is not currently published, but this should just start working when we do get it published to the marketplace.
@khawkins @sfdctaka @maliroteh-sf
=> Recommend the Offline Starter Kit Wizard extension.

.npmrc
=> Removing .npmrc which should not be needed.

.github/workflows/lint.yml, .github/workflows/prettier.yml, .github/workflows/run-tests.yml, force-app/main/default/lwc/accountRelatedContacts/accountRelatedContacts.js, force-app/main/default/lwc/createAccountRecord/__tests__/createAccountRecord.test.js, force-app/main/default/lwc/createContactRecord/__tests__/createContactRecord.test.js, force-app/main/default/lwc/createOpportunityRecord/__tests__/createOpportunityRecord.test.js, force-app/main/default/lwc/editAccountRecord/__tests__/editAccountRecord.test.js, force-app/main/default/lwc/fileUpload/fileUpload.js, force-app/main/default/lwc/locationService/__tests__/locationService.test.js, force-app/main/default/lwc/recordHeader/__tests__/recordHeader.test.js, force-app/main/default/lwc/scanBarcode/__tests__/scanBarcode.test.js, force-app/main/default/lwc/viewAccountsWithApex/__tests__/viewAccountsWithApex.test.js, package-lock.json, package.json, sfdx-project.json
Node 16 will hit end-of-life on 2023-09-11 so we need to move to v18
=> Upgrade to node 18

force-app/main/default/lwc/scanBarcodeLookUp/scanBarcodeLookUp.html, force-app/main/default/lwc/scanBarcodeLookUp/scanBarcodeLookUp.js, force-app/main/default/lwc/scanBarcodeLookUp/scanBarcodeLookUp.js-meta.xml, force-app/main/default/lwc/viewProduct2Record/__tests__/data/getRecord.json, force-app/main/default/lwc/viewProduct2Record/__tests__/viewProduct2Record.test.js, force-app/main/default/lwc/viewProduct2Record/viewProduct2Record.css, force-app/main/default/lwc/viewProduct2Record/viewProduct2Record.html, force-app/main/default/lwc/viewProduct2Record/viewProduct2Record.js, force-app/main/default/lwc/viewProduct2Record/viewProduct2Record.js-meta.xml, force-app/main/default/quickActions/Product2.view.quickAction-meta.xml
Created an example LWC that looks up a record with matching barcode and show the record.
=> Barcode scan record lookup example LWC

force-app/main/default/lwc/createContactRecord/__tests__/createContactRecord.test.js, force-app/main/default/lwc/createContactRecord/createContactRecord.html, force-app/main/default/lwc/createContactRecord/createContactRecord.js, package-lock.json, package.json
Create a field lookup example by using the base component lightning-record-picker.
The component is added in the `createContactRecord` LWC. When creating a contact, user can search accounts list and select one to be associated with the newly created contact.
https://github.com/salesforce/offline-app-developer-starter-kit/assets/6307038/61fa8f33-8f0a-473a-ad8b-ce53ca41cc49
=> Add a lookup field in createContactRecord

force-app/main/default/lwc/accountRelatedContacts/accountRelatedContacts.js-meta.xml, force-app/main/default/lwc/viewAccountRecord/viewAccountRecord.html, force-app/main/default/quickActions/Account.relatedContacts.quickAction-meta.xml
Expose the accountRelatedContacts LWC as a quick action
=> Account related contacts LWC quick action

README.md, docs/OfflineLookups.md
The document introduces the offline lookups feature. It also provides steps to setup and integrate the component.
=> Add offline lookups document

README.md, docs/CustomObject.md
The document introduces the custom object example. It also provides steps to configure a custom object.
=> Add document for custom object example

docs/RelatedRecords.md, force-app/main/default/lwc/accountRelatedContacts/accountRelatedContacts.js
Fixes issue where contacts are not being displayed offline
=> Fix prefetch issue while priming

docs/RelatedRecords.md
Removed if statement from GraphQL query code snippet to match current
=> Update Related Records document

force-app/main/default/lwc/createContactRecord/createContactRecord.js
Due to the recent changes, it results in an error when creating a contact record with the account lookup. This PR is to fix the error by adding back the accountField property.
=> Fix lookup error by adding back accountField property
